// CONSTANTES/ACCIONES QUE SE USARÁN EN EL PROYECTO.

export const GET_ALL_GAMES = 'GET_ALL_GAMES';
export const GET_GENRES = 'GET_GENRES';
export const GET_VIDEOGAME_DETAIL = 'GET_VIDEOGAME_DETAIL';
export const ORDER_BY_ALPHABET = 'ORDER_BY_ALPHABET';
export const ORDER_BY_RATING = 'ORDER_BY_RATING';
export const FILTER_BY_GENRES = 'FILTER_BY_GENRES';
export const FILTER_BY_INFO = 'FILTER_BY_INFO';
export const GET_VIDEOGAME_NAME = "GET_VIDEOGAME_NAME";
export const CLEAR_DETAILS = "CLEAR_DETAILS";
export const FILTER_BY_DATE = 'FILTER_BY_DATE';